### ISSUE TITLE
tcm pass seems to be removing `drv` instructions

### ISSUE THREAD

**Issue by eduardosm** [fabianschuiki/llhd#101] opened 2020-02-14 11:33 UTC
The tcm pass seems to be removing `drv` instructions in procs. If found this by running `llhd-opt` on `tests/opt_2.llhd`.

I have created a minimal example that reproduces the bug:

Running `llhd-opt -p tcm` on

```
proc @foo () -> (i1$ %out) {
0:
    %delta = const time 0s 1d
    %k0 = const i1 0
    drv i1$ %out, %k0, %delta
    br %0
}
```

produces

```
proc @foo () -> (i1$ %out) {
0:
    %delta = const time 0s 1d
    %k0 = const i1 0
    br %0
}
```

Running with `-vvvvv` produces the following trace:

```
DEBUG - Running ["tcm"]
TRACE - Running pass tcm
INFO - TCM [@foo]
TRACE - Constructing TRG:
TRACE -   Root bb0 (entry)
TRACE -   Pushing bb0 (t0)
TRACE -   Blocks: {
    bb0: t0,
}
TRACE - [DomTree] post-order [bb0]
TRACE - [DomTree] inv-post-order [0]
TRACE - [DomTree] initial [0]
TRACE - [DomTree] iteration [0]
TRACE - [DomTree] converged [0]
TRACE - [DomTree] final [bb0]
TRACE - Constructing TRG:
TRACE -   Root bb0 (entry)
TRACE -   Pushing bb0 (t0)
TRACE -   Blocks: {
    bb0: t0,
}
TRACE - Skipping t0 for wait merge (single wait inst)
TRACE - [DomTree] post-order [bb0]
TRACE - [DomTree] inv-post-order [0]
TRACE - [DomTree] initial [0]
TRACE - [DomTree] iteration [0]
TRACE - [DomTree] converged [0]
TRACE - [DomTree] final [bb0]
TRACE - Checking %0 for aliases
TRACE -   Drive %out (drv %out, %k0, %delta)
TRACE - Constructing TRG:
TRACE -   Root bb0 (entry)
TRACE -   Pushing bb0 (t0)
TRACE -   Blocks: {
    bb0: t0,
}
TRACE - Moving drives on signal %out
```

**Comment by eduardosm** [comment] 2020-02-14 11:41
After doing a `git bisect` between 0.11.0 and head, it seems that commit 652f411f2bc4b616c16b84a3ad03f8857fef893d caused this issue.

**Comment by eduardosm** [comment] 2020-02-14 11:46
Just found out this is a duplicate of https://github.com/fabianschuiki/llhd/issues/100 
I still hope that the minimal example and bisect is useful to you.

**Comment by fabianschuiki** [comment] 2020-02-14 11:56
Thanks for your report, the minimal example is useful! The issue seems to be in the temporal region graph computation, where in this case the temporal region is not assigned any tail blocks.

Will close this as duplicate of #100.

**Closed by fabianschuiki** 2020-02-14 11:56 UTC
